name: Deploy to wordress.org

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@2.0.0
      env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: helpful